apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://monitoring-kube-prometheus-prometheus.monitoring:9090
      access: proxy
      isDefault: true
    - name: Postgres-Overdue
      type: postgres
      url: $(OVERDUEFORECAST_POSTGRES_URL)
      database: overdueforecast
      user: $(OVERDUEFORECAST_USER)
      secureJsonData:
        password: $(OVERDUEFORECAST_PASSWORD)
    - name: Postgres-overbooking
      type: postgres
      url: $(OVERBOOKING_POSTGRESS_URL)
      database: overbooking
      user: $(OVERBOOOKING_USER)
      secureJsonData:
        password: $(OVERBOOKING_PASSWORD)
      jsonData:
        sslmode: "require" # disable/require/verify-ca/verify-full
        maxOpenConns: 1
        maxIdleConns: 5
        connMaxLifetime: 14400
        postgresVersion: 13
        timescaledb: false
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "1"
  name: grafana-datasource
