{
 "title": "AssPlan",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Uptime - Prod",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(up{namespace=\"logistics-assisted-pla-znkjx\", service!~\".*-staging$\"}) by (service)",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "max(flower_worker_online{namespace=\"logistics-assisted-pla-znkjx\",service=\"flower-service\"})",
     "legendFormat": "worker"
    }
   ]
  },
  {
   "title": "Uptime - Staging",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(up{namespace=\"logistics-assisted-pla-znkjx\", service=~\".*-staging$\"}) by (service)",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "max(flower_worker_online{namespace=\"logistics-assisted-pla-znkjx\",service=\"flower-service-staging\"})",
     "legendFormat": "worker-staging"
    }
   ]
  },
  {
   "title": "Worker task failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(flower_events_total{type=\"task-failed\", service=\"flower-service\"}[15m])"
    }
   ]
  },
  {
   "title": "Avg worker runtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(flower_task_runtime_seconds_sum{namespace=\"logistics-assisted-pla-znkjx\", service=\"flower-service\"}[5m])) by (task) / avg(rate(flower_task_runtime_seconds_count{namespace=\"logistics-assisted-pla-znkjx\", service=\"flower-service\"}[5m])) by (task)",
     "legendFormat": "PROD - {{task}}"
    }
   ]
  },
  {
   "title": "Number of tasks executing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "sum(flower_worker_number_of_currently_executing_tasks{namespace=\"logistics-assisted-pla-znkjx\", service=\"flower-service\"})"
    }
   ]
  },
  {
   "title": "Total items per DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=\"logistics-assisted-pla-znkjx\"}) by (service)"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{namespace=\"logistics-assisted-pla-znkjx\", service=\"redis-service\"}[15m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{namespace=\"logistics-assisted-pla-znkjx\", service=\"redis-service\"}[15m])",
     "legendFormat": "misses"
    }
   ]
  }
 ]
}