{
 "title": "Freight overbooking",
 "time": { "from": "now/M", "to": "now/M" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(n_times_predicted_immgot_by_end_user_counter{namespace=\"ferry-cancellation-for-jpoxj\", service=\"overbooking-api\"}[10y]))"
    },
    {
     "expr": "sum(increase(n_times_predicted_gnegot_by_end_user_counter{namespace=\"ferry-cancellation-for-jpoxj\", service=\"overbooking-api\"}[10y]))"
    },
    {
     "expr": "sum(increase(n_times_predicted_kpspln_by_end_user_counter{namespace=\"ferry-cancellation-for-jpoxj\", service=\"overbooking-api\"}[10y]))"
    }
   ]
  },
  {
   "title": "Times generated by user ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(n_times_predicted_by_end_user_total{namespace=\"ferry-cancellation-for-jpoxj\", service=\"overbooking-api\"}[10y]))"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Up time",
   "type": "state-timeline",
   "description": "Boolean returning 0 if down and 1 if up ",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "sum(up{namespace=\"ferry-cancellation-for-jpoxj\", service=\"overbooking-api\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"ferry-cancellation-for-jpoxj\", container=\"overbooking-frontend\"})",
     "legendFormat": "Frontend"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{namespace=\"ferry-cancellation-for-jpoxj\", service=\"overbooking-api\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{namespace=\"ferry-cancellation-for-jpoxj\",service=~\"overbooking-api\"}) ",
     "legendFormat": "Memory usages backend"
    }
   ]
  },
  {
   "title": "Number of predictions generated",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(n_row_times_generated_total{namespace=\"ferry-cancellation-for-jpoxj\", service=\"overbooking-api\"}[10y]))"
    }
   ]
  },
  {
   "title": "Times generated",
   "type": "stat",
   "description": "Shows the number of times that the model has been asked for predictions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(n_times_generated_total{namespace=\"ferry-cancellation-for-jpoxj\", service=\"overbooking-api\"}[10y]))"
    }
   ]
  },
  {
   "title": "Predictions",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 23, "x": 1, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum by (le)(OB_predictions_bucket{le!=\"+Inf\"})",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}